apiVersion: v1
kind: Pod
metadata:
  name: pytorch-pod
spec:
  containers:
  - name: gpu-container
    image: ufoym/deepo:pytorch-py36-cu101
    command: ["sleep", "infinity"]
    resources:
      limits:
        cpu: 2
        nvidia.com/gpu: 1
        memory: 8Gi
      requests:
        cpu: 1
        memory: 8Gi
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /storage-pod
      name: storage-pod
  restartPolicy: Never
  volumes:
    - name: storage-pod
      persistentVolumeClaim:
        claimName: storage-pod