apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-pod
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nautilus.optiputer.net/prp/jupyterlab:latest
    command: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: 8Gi
        cpu: 2
      requests:
        memory: 8Gi
        cpu: 1
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /storage-pod
      name: storage-pod
  restartPolicy: Never
  volumes:
    - name: storage-pod
      persistentVolumeClaim:
        claimName: storage-pod